### ISSUE TITLE
TEMP leads to crosstalk of the relay logic

### ISSUE THREAD

**Issue by nkrackow** [sinara-hw/Laser_Module#1]
https://github.com/sinara-hw/Driver/issues/3#issuecomment-1132693073 
This still applies. Maybe just a double negation with two NPNs per Driver channel? Or a PNP.

Might be related to:
> We would really like to also have control over the TEMP node from the CPU. The best would be if the TEMP node is usually pulled low (aka overwriting the relay logic and forcing the laser diode to be shorted) until a CPU pin goes high. 

from https://github.com/sinara-hw/Driver/issues/6

**Comment by gkasprow** [comment]
I think it was already fixed

**Comment by nkrackow** [comment]
Yes this was fixed for the first physical board.
